### ISSUE TITLE
Update the README.md

### ISSUE THREAD

**Issue by ciaraMagAoidh** [ciaraMagAoidh/data-visualisation-belfast-trees#5]
Tasks
- [x] copy the intro_setup contents to the project README.md
- [x] update internal project links

**Comment by Carlscc** [comment]
Done, also:

- [x] Would you please change the markdown folder to something more obvious like 'tasks'? (I'll update the README task relative links again when this is done).

- [x] Please delete the previous intro doc from that folder, else it is duplicated.

Thanks

**Comment by ciaraMagAoidh** [comment]
Changed 'Tasks' to 'Activities'
